### ISSUE TITLE
Search only shows one page of results

### ISSUE THREAD

**Issue by fmw42** [macports/macports-webapp#137] opened 2019-11-11 03:53 UTC
When I search available ports for "py37",  I only get some of the links listed and no way to get to more of them further down the alphabet. There is no list of pages buttons.

Using Mac OSX Safari 12.1.2 on Sierra 10.12.6

[Ports | MacPorts Bug Report.pdf](https://github.com/macports/macports-webapp/files/3829637/Ports.MacPorts.Bug.Report.pdf)
 or even a next button.

**Comment by ryandesign** [comment] 2019-11-29 08:21
Duplicate of #86?

**Comment by cjones051073** [comment] 2020-01-20 19:42
> Duplicate of #86?

Not quite, I would say. That issue is more about the order being unpredictable and not particularly useful. This issue is the fact you cannot get mire results than those that just so happen to make it into the selected list. Both these issues need addressing to make the search function useful.

**Comment by mojca** [comment] 2021-07-21 22:55
After the search page has basically been rewritten from scratch, I believe that the problem has been addressed. If there's something left, please reopen the ticket or open a new one.

**Closed as completed by mojca** 2021-07-21 22:55 UTC
Labels: bug
